apiVersion: batch/v1
kind: Job
metadata:
  name: cassandra-init
spec:
  template:
    spec:
      containers:
      - name: cassandra-init
        image: anierbeck/bus-demo-schema:0.5.0-SNAPSHOT
        command: ["/opt/bus-demo/import_data.sh", "cassandra"]
      restartPolicy: Never